package fr.nhsoul.natsbridge.core.subscription;

import org.jetbrains.annotations.NotNull;

import java.lang.reflect.Method;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Manager interface for NATS subscriptions.
 * <p>
 * This interface defines the contract for managing NATS subscriptions,
 * including registration, scanning, and lifecycle management.
 * </p>
 *
 * <h2>Responsibilities</h2>
 * <ul>
 *   <li>Scanning plugins for @NatsSubscribe annotations</li>
 *   <li>Registering method-based and consumer-based subscriptions</li>
 *   <li>Loading generated subscriptions from annotation processor</li>
 *   <li>Managing subscription lifecycle (activate/deactivate)</li>
 *   <li>Resource cleanup and shutdown</li>
 * </ul>
 */
public interface SubscriptionManager {

    /**
     * Scans an object for @NatsSubscribe annotations and registers them.
     *
     * @param plugin the plugin instance to scan
     */
    void scanAndRegister(@NotNull Object plugin);

    /**
     * Registers a method-based subscription.
     *
     * @param pluginInstance the plugin instance containing the method
     * @param method the method to invoke when messages are received
     * @param subject the NATS subject to subscribe to
     * @param async whether to process messages asynchronously
     */
    void registerSubscription(@NotNull Object pluginInstance,
                            @NotNull Method method,
                            @NotNull String subject,
                            boolean async);

    /**
     * Registers a consumer-based subscription.
     *
     * @param subject the NATS subject to subscribe to
     * @param consumer the consumer to process incoming messages
     * @param async whether to process messages asynchronously
     */
    void registerConsumerSubscription(@NotNull String subject,
                                    @NotNull Consumer<byte[]> consumer,
                                    boolean async);

    /**
     * Loads subscriptions generated by the annotation processor.
     *
     * @param pluginRegistry a map of plugin classes to their instances
     */
    void loadGeneratedSubscriptions(@NotNull Map<Class<?>, Object> pluginRegistry);

    /**
     * Activates all registered subscriptions.
     * <p>
     * This should be called when the NATS connection is established.
     * </p>
     */
    void subscribeAll();

    /**
     * Unsubscribes from a specific NATS subject.
     *
     * @param subject the subject to unsubscribe from
     */
    void unsubscribe(@NotNull String subject);

    /**
     * Unsubscribes from all NATS subjects.
     */
    void unsubscribeAll();

    /**
     * Shuts down the subscription manager and cleans up resources.
     */
    void shutdown();
}